### ISSUE TITLE
[Erro] Não consigo usar quase nenhum método da classe Account

### ISSUE THREAD

**Issue by willmustafa** [fmsouza/nubank-api#23]
Fiz o login, tudo certo.

Crio a classe com :

```
const api = new NubankApi({
  ...authState
});
```

e depois puxo os métodos.
Consigo acesso apenas a esses métodos: `api.card.getFeed()` e `api.account.getBills()`.

Se eu tento o `api.account.getInvestments()` dá esse erro:

```
/home/willian/Documents/GitHub/Money7-API-RESTFUL/node_modules/nubank-api/lib/utils/http.js:222
                        throw (_a = error.response.data.errors[0]) !== null && _a !== void 0 ? _a : error;
                                                              ^

TypeError: Cannot read properties of undefined (reading '0')
    at Http.<anonymous> (/home/willian/Documents/GitHub/Money7-API-RESTFUL/node_modules/nubank-api/lib/utils/http.js:222:63)
    at step (/home/willian/Documents/GitHub/Money7-API-RESTFUL/node_modules/nubank-api/lib/utils/http.js:44:23)
    at Object.throw (/home/willian/Documents/GitHub/Money7-API-RESTFUL/node_modules/nubank-api/lib/utils/http.js:25:53)
    at rejected (/home/willian/Documents/GitHub/Money7-API-RESTFUL/node_modules/nubank-api/lib/utils/http.js:17:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by victorratts13** [comment]
Provavelmente esta biblioteca foi abandonada depois de uma atualização da api do nubank. Estou desenvolvendo uma API do zero com a finalidade de englobar os principais bancos.

**Comment by fmsouza** [comment]
@willmustafa @victorratts13  desculpa a demora pra responder.

Essa lib é trabalho voluntário e sem "nenhuma ajuda" externa. Se você for lá na aba de "Insights" do repositório você vai ver que praticamente só tem commit meu e pouca coisa de ajuda de outras pessoas. Não tenho nenhum patrocínio nem incentivos externos pra continuar tocando o projeto. Eu tinha começado pra atender uma necessidade minha mesmo de gestão da minha conta mesmo, e o código ta aberto porque sempre achei útil entregar pra comunidade utilizar como quiser.

Dito isso, essa API não foi "abandonada depois de uma atualização do nubank". A última vez que trabalhei nela (17 de março) tudo ainda funcionava. O que pode ter acontecido é introdução de algum bug com alguma mudança. Mas dado que tenho uma vida fora das minhas contribuições ao OSS e não tenho incentivo nenhum para trabalhar aqui (nem uso mais minha conta do Nubank), realmente não tenho investido muito tempo na lib.

No entanto, se estiver sendo útil para vocês (e fico realmente muito feliz por isso), vocês sempre vão poder abrir issues para reportar problemas e abrir PRs as solucionando. Também podem fazer forks... Enfim, o código é aberto para a comunidade modificar e fazer essa integração continuar funcionando :)

**Comment by victorratts13** [comment]
@fmsouza Obg pela resposta. E principalmente pela iniciativa de criar a ferramenta. Desculpe se minha resposta anterior pareceu grosseira de alguma forma 🤝
